name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      continue-on-error: true
      with:
        sarif_file: 'trivy-results.sarif'
        category: 'trivy'
        
    - name: Save Trivy results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-security-results
        path: trivy-results.sarif
        retention-days: 30

  tfsec-scan:
    name: TfSec Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        soft_fail: true
      
    - name: Save TfSec results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tfsec-security-results
        path: |
          **/*.sarif
          **/tfsec-*.json
        retention-days: 30

  checkov-scan:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Checkov action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        output_format: sarif
        output_file_path: checkov-results.sarif
        soft_fail: true

    - name: Upload Checkov scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      continue-on-error: true
      with:
        sarif_file: checkov-results.sarif
        category: 'checkov'
        
    - name: Save Checkov results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: checkov-security-results
        path: checkov-results.sarif
        retention-days: 30
